version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install uv
      - pip install uv
    post_install:
      # Install dependencies with 'docs' dependency group
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --group docs --link-mode=copy

sphinx:
  configuration: docs/conf.py
