# Generated by Django 2.2 on 2021-03-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0029_auto_20210329_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociogrpcerrors',
            name='details',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Error Description'),
        ),
        migrations.AlterField(
            model_name='grcpprotobuffields',
            name='is_query',
            field=models.BooleanField(default=False, verbose_name='Query'),
        ),
        migrations.AlterField(
            model_name='grcpprotobuffields',
            name='is_update',
            field=models.BooleanField(default=False, verbose_name='Update'),
        ),
        migrations.AlterField(
            model_name='sociogrpcerrors',
            name='query',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Service Input'),
        ),
    ]
