# Generated by Django 2.2 on 2021-03-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0030_auto_20210329_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grcpdatabases',
            name='django',
            field=models.CharField(choices=[('django.contrib.admin', 'Administration'), ('django.contrib.auth', 'Authentication and Authorization'), ('django.contrib.contenttypes', 'Content Types'), ('django.contrib.sessions', 'Sessions'), ('django.contrib.messages', 'Messages'), ('django.contrib.staticfiles', 'Static Files'), ('django_grpc_framework', 'Django_Grpc_Framework'), ('fcm_django', 'FCM Django'), ('carcheck', 'Carcheck'), ('notification', 'Notification'), ('user', 'User'), ('utils', 'Utils')], db_index=True, default='', max_length=40, verbose_name='Django Application'),
        ),
        migrations.AlterField(
            model_name='sociogrpcerrors',
            name='method',
            field=models.IntegerField(choices=[(1, 'List'), (2, 'Create'), (3, 'Retrieve'), (4, 'Update'), (5, 'Destroy'), (6, 'Custom')], default=0),
        ),
    ]
