# Generated by Django 2.2 on 2021-04-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0034_generallog_speciallog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generallog',
            options={'verbose_name': 'DJANGO SYSTEM LOG', 'verbose_name_plural': 'DJANGO SYSTEM LOGS'},
        ),
        migrations.AlterModelOptions(
            name='speciallog',
            options={'verbose_name': 'DJANGO SYSTEM LOG', 'verbose_name_plural': 'DJANGO SYSTEM LOGS'},
        ),
        migrations.AddField(
            model_name='grpclogging',
            name='level',
            field=models.IntegerField(choices=[(1, 'DEBUG'), (2, 'INFO'), (3, 'WARNING'), (4, 'ERROR'), (5, 'CRITICAL')], default=0, verbose_name='Log Level'),
        ),
    ]
