# Generated by Django 2.2 on 2021-04-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0035_auto_20210402_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='grpclogging',
            name='port',
            field=models.IntegerField(default=0, verbose_name='gRPC Port'),
        ),
    ]
