# Generated by Django 2.2 on 2021-04-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0036_grpclogging_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='grpclogging',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
