# Generated by Django 2.2 on 2021-04-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0038_grpclogging_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='grpclogging',
            name='error',
            field=models.IntegerField(default=0, verbose_name='gRPC Error'),
        ),
    ]
