# Generated by Django 2.2 on 2021-04-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_grpc_framework', '0039_grpclogging_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='grpclogging',
            name='reason',
            field=models.CharField(db_index=True, default='', max_length=250, verbose_name='Reason Error'),
        ),
    ]
