# Generated by Django 3.2.11 on 2022-01-28 10:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("fakeapp", "0007_auto_20210503_1516"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlugTestModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("special_number", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="importstructeveninarraymodel",
            name="id",
        ),
        migrations.AddField(
            model_name="importstructeveninarraymodel",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="SlugReverseTestModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "related_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slug_reverse_test_model",
                        to="fakeapp.relatedfieldmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="relatedfieldmodel",
            name="slug_test_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related",
                to="fakeapp.slugtestmodel",
            ),
        ),
    ]
