# Generated by Django 4.0.6 on 2022-09-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeapp', '0009_specialfieldsmodel_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedfieldmodel',
            name='slug_many_many',
            field=models.ManyToManyField(blank=True, related_name='relateds_slugs', to='fakeapp.manymanymodel'),
        ),
    ]
