# Generated by Django 4.1.4 on 2023-01-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeapp', '0010_relatedfieldmodel_slug_many_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedfieldmodel',
            name='many_many_foreigns',
            field=models.ManyToManyField(blank=True, related_name='related_foreigns', to='fakeapp.relatedfieldmodel'),
        ),
        migrations.AlterField(
            model_name='unittestmodel',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
