# Generated by Django 4.2.8 on 2024-01-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeapp', '0012_recursivetestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultValueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_required', models.CharField(max_length=20)),
                ('string_blank', models.CharField(blank=True, max_length=20)),
                ('string_nullable', models.CharField(max_length=20, null=True)),
                ('string_default', models.CharField(default='default', max_length=20)),
                ('string_default_and_blank', models.CharField(blank=True, default='default_and_blank', max_length=60)),
                ('string_null_default_and_blank', models.CharField(blank=True, default='null_default_and_blank', max_length=60, null=True)),
                ('string_required_but_serializer_default', models.CharField(max_length=20)),
                ('string_default_but_serializer_default', models.CharField(default='default', max_length=60)),
                ('string_nullable_default_but_serializer_default', models.CharField(default='default', max_length=60)),
                ('int_required', models.IntegerField()),
                ('int_nullable', models.IntegerField(null=True)),
                ('int_default', models.IntegerField(default=5)),
                ('int_required_but_serializer_default', models.IntegerField()),
                ('boolean_required', models.BooleanField()),
                ('boolean_nullable', models.BooleanField(null=True)),
                ('boolean_default_false', models.BooleanField(default=False)),
                ('boolean_default_true', models.BooleanField(default=True)),
                ('boolean_required_but_serializer_default', models.BooleanField()),
            ],
        ),
    ]
