# Generated by Django 4.2.8 on 2023-12-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeapp', '0012_recursivetestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedfieldmodel',
            name='many_many_other',
            field=models.ManyToManyField(blank=True, related_name='relateds_other', to='fakeapp.manymanymodel'),
        ),
    ]
