# Generated by Django 4.2.8 on 2024-01-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeapp', '0012_recursivetestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittestmodel',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unittestmodel',
            name='some_default_counter',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
