# Generated by Django 4.2.11 on 2024-10-24 08:09

from django.db import migrations, models
import fakeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("fakeapp", "0013_defaultvaluemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnumModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char_choices",
                    models.CharField(
                        choices=[
                            fakeapp.models.EnumModel.MyTestStrEnum["VALUE_1"],
                            fakeapp.models.EnumModel.MyTestStrEnum["VALUE_2"],
                        ]
                    ),
                ),
                (
                    "int_choices",
                    models.IntegerField(
                        choices=[
                            fakeapp.models.EnumModel.MyTestIntEnum["ONE"],
                            fakeapp.models.EnumModel.MyTestIntEnum["TWO"],
                        ]
                    ),
                ),
            ],
        ),
    ]
