# Generated by Django 5.0 on 2024-10-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fakeapp", "0013_defaultvaluemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnumModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char_choices",
                    models.CharField(
                        choices=[
                            ("VALUE_1", "Human readable value 1"),
                            ("VALUE_2", "Human readable value 2"),
                        ]
                    ),
                ),
            ],
        ),
    ]
