# Generated by Django 5.0 on 2024-10-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fakeapp", "0014_enummodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="enummodel",
            name="int_choices",
            field=models.IntegerField(
                choices=[(1, "Human readable 1"), (2, "Human readable 2")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="enummodel",
            name="char_choices",
            field=models.CharField(
                choices=[
                    ("VALUE_1", "Human readable value 1"),
                    ("VALUE_2", "Human readable value 2"),
                ],
                default="VALUE_1",
            ),
        ),
    ]
