# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: django_socio_grpc/protobuf/tests/protos/test_proto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n8django_socio_grpc/protobuf/tests/protos/test_proto.proto\x12\x0ctest.package"\xb4\x01\n\tMyMessage\x12\x14\n\x0cstring_field\x18\x01 \x01(\t\x12"\n\x15optional_string_field\x18\x02 \x01(\tH\x02\x88\x01\x01\x12\x10\n\x06\x66ield1\x18\x03 \x01(\tH\x00\x12\x10\n\x06\x66ield2\x18\x04 \x01(\tH\x01\x12\x10\n\x06\x66ield3\x18\x05 \x01(\tH\x01\x42\r\n\x0boneof_fieldB\x0e\n\x0coneof_field2B\x18\n\x16_optional_string_fieldb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "django_socio_grpc.protobuf.tests.protos.test_proto_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _MYMESSAGE._serialized_start = 75
    _MYMESSAGE._serialized_end = 255
# @@protoc_insertion_point(module_scope)
