# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from generate_proto_doc.grpc import generate_proto_doc_pb2 as generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class SomethingControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/doc_example.generate_proto_doc.SomethingController/List',
                request_serializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoListRequest.SerializeToString,
                response_deserializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoListResponse.FromString,
                )
        self.Create = channel.unary_unary(
                '/doc_example.generate_proto_doc.SomethingController/Create',
                request_serializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoRequest.SerializeToString,
                response_deserializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/doc_example.generate_proto_doc.SomethingController/Retrieve',
                request_serializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoRetrieveRequest.SerializeToString,
                response_deserializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/doc_example.generate_proto_doc.SomethingController/Update',
                request_serializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoRequest.SerializeToString,
                response_deserializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/doc_example.generate_proto_doc.SomethingController/Destroy',
                request_serializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class SomethingControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SomethingControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoListRequest.FromString,
                    response_serializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoListResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoRequest.FromString,
                    response_serializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoRetrieveRequest.FromString,
                    response_serializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoRequest.FromString,
                    response_serializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'doc_example.generate_proto_doc.SomethingController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SomethingController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/doc_example.generate_proto_doc.SomethingController/List',
            generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoListRequest.SerializeToString,
            generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/doc_example.generate_proto_doc.SomethingController/Create',
            generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoRequest.SerializeToString,
            generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/doc_example.generate_proto_doc.SomethingController/Retrieve',
            generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoRetrieveRequest.SerializeToString,
            generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/doc_example.generate_proto_doc.SomethingController/Update',
            generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoRequest.SerializeToString,
            generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/doc_example.generate_proto_doc.SomethingController/Destroy',
            generate__proto__doc_dot_grpc_dot_generate__proto__doc__pb2.SomethingProtoDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
