# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generate_proto_doc/grpc/generate_proto_doc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='generate_proto_doc/grpc/generate_proto_doc.proto',
  package='doc_example.generate_proto_doc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0generate_proto_doc/grpc/generate_proto_doc.proto\x12\x1e\x64oc_example.generate_proto_doc\x1a\x1bgoogle/protobuf/empty.proto\"H\n\x16SomethingProtoResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x0c\n\x04rate\x18\x03 \x01(\t\"\x1b\n\x19SomethingProtoListRequest\"e\n\x1aSomethingProtoListResponse\x12G\n\x07results\x18\x01 \x03(\x0b\x32\x36.doc_example.generate_proto_doc.SomethingProtoResponse\"G\n\x15SomethingProtoRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x0c\n\x04rate\x18\x03 \x01(\t\"-\n\x1dSomethingProtoRetrieveRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\",\n\x1cSomethingProtoDestroyRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t2\xf5\x04\n\x13SomethingController\x12\x7f\n\x04List\x12\x39.doc_example.generate_proto_doc.SomethingProtoListRequest\x1a:.doc_example.generate_proto_doc.SomethingProtoListResponse\"\x00\x12y\n\x06\x43reate\x12\x35.doc_example.generate_proto_doc.SomethingProtoRequest\x1a\x36.doc_example.generate_proto_doc.SomethingProtoResponse\"\x00\x12\x83\x01\n\x08Retrieve\x12=.doc_example.generate_proto_doc.SomethingProtoRetrieveRequest\x1a\x36.doc_example.generate_proto_doc.SomethingProtoResponse\"\x00\x12y\n\x06Update\x12\x35.doc_example.generate_proto_doc.SomethingProtoRequest\x1a\x36.doc_example.generate_proto_doc.SomethingProtoResponse\"\x00\x12\x61\n\x07\x44\x65stroy\x12<.doc_example.generate_proto_doc.SomethingProtoDestroyRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SOMETHINGPROTORESPONSE = _descriptor.Descriptor(
  name='SomethingProtoResponse',
  full_name='doc_example.generate_proto_doc.SomethingProtoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='doc_example.generate_proto_doc.SomethingProtoResponse.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_date', full_name='doc_example.generate_proto_doc.SomethingProtoResponse.start_date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rate', full_name='doc_example.generate_proto_doc.SomethingProtoResponse.rate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=185,
)


_SOMETHINGPROTOLISTREQUEST = _descriptor.Descriptor(
  name='SomethingProtoListRequest',
  full_name='doc_example.generate_proto_doc.SomethingProtoListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=214,
)


_SOMETHINGPROTOLISTRESPONSE = _descriptor.Descriptor(
  name='SomethingProtoListResponse',
  full_name='doc_example.generate_proto_doc.SomethingProtoListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='doc_example.generate_proto_doc.SomethingProtoListResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=317,
)


_SOMETHINGPROTOREQUEST = _descriptor.Descriptor(
  name='SomethingProtoRequest',
  full_name='doc_example.generate_proto_doc.SomethingProtoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='doc_example.generate_proto_doc.SomethingProtoRequest.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_date', full_name='doc_example.generate_proto_doc.SomethingProtoRequest.start_date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rate', full_name='doc_example.generate_proto_doc.SomethingProtoRequest.rate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=390,
)


_SOMETHINGPROTORETRIEVEREQUEST = _descriptor.Descriptor(
  name='SomethingProtoRetrieveRequest',
  full_name='doc_example.generate_proto_doc.SomethingProtoRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='doc_example.generate_proto_doc.SomethingProtoRetrieveRequest.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=437,
)


_SOMETHINGPROTODESTROYREQUEST = _descriptor.Descriptor(
  name='SomethingProtoDestroyRequest',
  full_name='doc_example.generate_proto_doc.SomethingProtoDestroyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='doc_example.generate_proto_doc.SomethingProtoDestroyRequest.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=483,
)

_SOMETHINGPROTOLISTRESPONSE.fields_by_name['results'].message_type = _SOMETHINGPROTORESPONSE
DESCRIPTOR.message_types_by_name['SomethingProtoResponse'] = _SOMETHINGPROTORESPONSE
DESCRIPTOR.message_types_by_name['SomethingProtoListRequest'] = _SOMETHINGPROTOLISTREQUEST
DESCRIPTOR.message_types_by_name['SomethingProtoListResponse'] = _SOMETHINGPROTOLISTRESPONSE
DESCRIPTOR.message_types_by_name['SomethingProtoRequest'] = _SOMETHINGPROTOREQUEST
DESCRIPTOR.message_types_by_name['SomethingProtoRetrieveRequest'] = _SOMETHINGPROTORETRIEVEREQUEST
DESCRIPTOR.message_types_by_name['SomethingProtoDestroyRequest'] = _SOMETHINGPROTODESTROYREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SomethingProtoResponse = _reflection.GeneratedProtocolMessageType('SomethingProtoResponse', (_message.Message,), {
  'DESCRIPTOR' : _SOMETHINGPROTORESPONSE,
  '__module__' : 'generate_proto_doc.grpc.generate_proto_doc_pb2'
  # @@protoc_insertion_point(class_scope:doc_example.generate_proto_doc.SomethingProtoResponse)
  })
_sym_db.RegisterMessage(SomethingProtoResponse)

SomethingProtoListRequest = _reflection.GeneratedProtocolMessageType('SomethingProtoListRequest', (_message.Message,), {
  'DESCRIPTOR' : _SOMETHINGPROTOLISTREQUEST,
  '__module__' : 'generate_proto_doc.grpc.generate_proto_doc_pb2'
  # @@protoc_insertion_point(class_scope:doc_example.generate_proto_doc.SomethingProtoListRequest)
  })
_sym_db.RegisterMessage(SomethingProtoListRequest)

SomethingProtoListResponse = _reflection.GeneratedProtocolMessageType('SomethingProtoListResponse', (_message.Message,), {
  'DESCRIPTOR' : _SOMETHINGPROTOLISTRESPONSE,
  '__module__' : 'generate_proto_doc.grpc.generate_proto_doc_pb2'
  # @@protoc_insertion_point(class_scope:doc_example.generate_proto_doc.SomethingProtoListResponse)
  })
_sym_db.RegisterMessage(SomethingProtoListResponse)

SomethingProtoRequest = _reflection.GeneratedProtocolMessageType('SomethingProtoRequest', (_message.Message,), {
  'DESCRIPTOR' : _SOMETHINGPROTOREQUEST,
  '__module__' : 'generate_proto_doc.grpc.generate_proto_doc_pb2'
  # @@protoc_insertion_point(class_scope:doc_example.generate_proto_doc.SomethingProtoRequest)
  })
_sym_db.RegisterMessage(SomethingProtoRequest)

SomethingProtoRetrieveRequest = _reflection.GeneratedProtocolMessageType('SomethingProtoRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _SOMETHINGPROTORETRIEVEREQUEST,
  '__module__' : 'generate_proto_doc.grpc.generate_proto_doc_pb2'
  # @@protoc_insertion_point(class_scope:doc_example.generate_proto_doc.SomethingProtoRetrieveRequest)
  })
_sym_db.RegisterMessage(SomethingProtoRetrieveRequest)

SomethingProtoDestroyRequest = _reflection.GeneratedProtocolMessageType('SomethingProtoDestroyRequest', (_message.Message,), {
  'DESCRIPTOR' : _SOMETHINGPROTODESTROYREQUEST,
  '__module__' : 'generate_proto_doc.grpc.generate_proto_doc_pb2'
  # @@protoc_insertion_point(class_scope:doc_example.generate_proto_doc.SomethingProtoDestroyRequest)
  })
_sym_db.RegisterMessage(SomethingProtoDestroyRequest)



_SOMETHINGCONTROLLER = _descriptor.ServiceDescriptor(
  name='SomethingController',
  full_name='doc_example.generate_proto_doc.SomethingController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=486,
  serialized_end=1115,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='doc_example.generate_proto_doc.SomethingController.List',
    index=0,
    containing_service=None,
    input_type=_SOMETHINGPROTOLISTREQUEST,
    output_type=_SOMETHINGPROTOLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='doc_example.generate_proto_doc.SomethingController.Create',
    index=1,
    containing_service=None,
    input_type=_SOMETHINGPROTOREQUEST,
    output_type=_SOMETHINGPROTORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='doc_example.generate_proto_doc.SomethingController.Retrieve',
    index=2,
    containing_service=None,
    input_type=_SOMETHINGPROTORETRIEVEREQUEST,
    output_type=_SOMETHINGPROTORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='doc_example.generate_proto_doc.SomethingController.Update',
    index=3,
    containing_service=None,
    input_type=_SOMETHINGPROTOREQUEST,
    output_type=_SOMETHINGPROTORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='doc_example.generate_proto_doc.SomethingController.Destroy',
    index=4,
    containing_service=None,
    input_type=_SOMETHINGPROTODESTROYREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOMETHINGCONTROLLER)

DESCRIPTOR.services_by_name['SomethingController'] = _SOMETHINGCONTROLLER

# @@protoc_insertion_point(module_scope)
