version: "3.1"

services:
  doc_example:
    image: doc_example
    tty: true
    build:
      context: .
    environment:
      - DB_NAME=test
      - DB_USER=test
      - DB_PASSWORD=test_pw
      - DB_HOST=test-database
    # command: /opt/code/manage.py grpcrunaioserver 0.0.0.0:30000 --dev
    command: /opt/code/manage.py generateproto
    links:
      - test-database
    volumes:
      - .:/opt/code
    ports:
      - "30000:30000"
    networks:
      doc_example-network:

  test-database:
    image: library/postgres:11.5
    # ports:
    #   - "5532:5432"
    volumes:
      - /srv/doc_example/database/doc_example:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test_pw
    networks:
      doc_example-network:

networks:
  doc_example-network:
